<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>total cart after discount</name>
  <uuid>a4aec598-6e14-4cfd-9157-fb3d07a3671f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to min( 'the discount on cart total' , 'the total after discount on products' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
