<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ba210b8f-02dc-4a95-9573-77c65671d8b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to " We don't have correct information to greet you!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
