<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>salutation</name>
  <uuid>7891b97a-400b-4e03-95df-7ba74eea8e39</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the greeting' + ", " + 'the courtesy title' + " " + 'the name' + "!" ;
print decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
