<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>init</name>
  <uuid>00ae5e1e-e319-4ee8-8a9d-63f0fe39d9d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the shopping cart' ; 
for each Item called 'item' , in the items of decision :
   - set the total line of item to the unit price of item * the quantity of item , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
